/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ucuenca.p3.UI;

import edu.ucuenca.p3.SRV.ClaveSRV;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.BadPaddingException;
import javax.crypto.IllegalBlockSizeException;
import javax.crypto.NoSuchPaddingException;
import javax.swing.JOptionPane;

/**
 *
 * @author andre
 */
public class AccesoUsuarioGUI extends javax.swing.JFrame {

    /**
     * Creates new form AccesoUsuarioGUI
     */
    private static AccesoUsuarioGUI instancia;

    private AccesoUsuarioGUI() {
        initComponents();
        System.out.println("Torneo de tenis ");
        ClaveSRV claveSrv = new ClaveSRV();
        claveSrv.cargarClaves();
        setLocationRelativeTo(null);
    }

    public static AccesoUsuarioGUI getInstancia() {
        if (instancia == null) {
            return instancia = new AccesoUsuarioGUI();
        }
        return instancia;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox_Usuario = new javax.swing.JComboBox();
        jPasswordField_Clave_Usuario = new javax.swing.JPasswordField();
        jButton_Ingresar = new javax.swing.JButton();
        jButton_Salir = new javax.swing.JButton();
        jButton_Registrar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Acceder como : ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 130, 38));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Clave :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 130, 38));

        jComboBox_Usuario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrador", "Árbitro", "Jugador" }));
        jComboBox_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_UsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 137, 38));
        getContentPane().add(jPasswordField_Clave_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 137, 38));

        jButton_Ingresar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_Ingresar.setText("Ingresar");
        jButton_Ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_IngresarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 127, 34));

        jButton_Salir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_Salir.setText("Salir");
        jButton_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 285, 34));

        jButton_Registrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_Registrar.setText("Registrar");
        jButton_Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 137, 34));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 290, 10));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ucuenca/p3/Iconos/fondo10.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_IngresarActionPerformed
        try {
            String usuario = (String) jComboBox_Usuario.getSelectedItem();
            String clave = jPasswordField_Clave_Usuario.getText();
            ClaveSRV claveSrv = new ClaveSRV();

            if (usuario.equalsIgnoreCase("Jugador")) {
                Pantalla_Principal_Ranking.getInstancia().show();
                AccesoUsuarioGUI.getInstancia().hide();
            } else {
                if (claveSrv.ingresoUsuario(clave, usuario)) {
                    if (usuario.equalsIgnoreCase("Administrador")) {
                        Pantalla_Principal_Admin.getInstancia().show();
                        AccesoUsuarioGUI.getInstancia().hide();
                    } else {
                        Pantalla_Principal_Torneos.getInstancia().show();
                        AccesoUsuarioGUI.getInstancia().hide();

                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Acceso denegado !");
                }
            }
            jPasswordField_Clave_Usuario.setText("");
        } catch (NoSuchPaddingException ex) {
            Logger.getLogger(AccesoUsuarioGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InvalidKeyException ex) {
            Logger.getLogger(AccesoUsuarioGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalBlockSizeException ex) {
            Logger.getLogger(AccesoUsuarioGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (BadPaddingException ex) {
            Logger.getLogger(AccesoUsuarioGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(AccesoUsuarioGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_IngresarActionPerformed

    private void jButton_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton_SalirActionPerformed

    private void jButton_RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RegistrarActionPerformed

        try {
            String tipoUsuario = (String) jComboBox_Usuario.getSelectedItem();
            String clave = jPasswordField_Clave_Usuario.getText();
            ClaveSRV claveSrv = new ClaveSRV();
            claveSrv.agregarUsuario(tipoUsuario);

            jPasswordField_Clave_Usuario.setText("");

        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());

        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(AccesoUsuarioGUI.class
                    .getName()).log(Level.SEVERE, null, ex);

        } catch (NoSuchPaddingException ex) {
            Logger.getLogger(AccesoUsuarioGUI.class
                    .getName()).log(Level.SEVERE, null, ex);

        } catch (InvalidKeyException ex) {
            Logger.getLogger(AccesoUsuarioGUI.class
                    .getName()).log(Level.SEVERE, null, ex);

        } catch (IllegalBlockSizeException ex) {
            Logger.getLogger(AccesoUsuarioGUI.class
                    .getName()).log(Level.SEVERE, null, ex);

        } catch (BadPaddingException ex) {
            Logger.getLogger(AccesoUsuarioGUI.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_RegistrarActionPerformed

    private void jComboBox_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_UsuarioActionPerformed
        String seleccion = jComboBox_Usuario.getSelectedItem().toString();
        if (seleccion.equalsIgnoreCase("Jugador")) {
            jButton_Registrar.setEnabled(false);
            jPasswordField_Clave_Usuario.setEnabled(false);
        }else{
            jPasswordField_Clave_Usuario.setEnabled(true);
        }
    }//GEN-LAST:event_jComboBox_UsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccesoUsuarioGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccesoUsuarioGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccesoUsuarioGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccesoUsuarioGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccesoUsuarioGUI().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Ingresar;
    private javax.swing.JButton jButton_Registrar;
    private javax.swing.JButton jButton_Salir;
    private javax.swing.JComboBox jComboBox_Usuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField_Clave_Usuario;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
