/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ucuenca.p3.UI;

import edu.ucuenca.p3.DAO.TorneoDAO;
import edu.ucuenca.p3.DAO.exceptions.TorneoExistenteExcepcion;
import edu.ucuenca.p3.Modulos.Categoria;
import edu.ucuenca.p3.Modulos.Torneo;
import edu.ucuenca.p3.SRV.TorneoSRV;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author andre
 */
public class TorneoGUI extends javax.swing.JPanel {

    /**
     * Creates new form TorneoGUI
     */
    int contador_torneos = 1;

    public TorneoGUI() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        radioZonal1 = new javax.swing.JRadioButton();
        radioNacional1 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        radioSimple = new javax.swing.JRadioButton();
        radioDoble = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        radioAbierto = new javax.swing.JRadioButton();
        radioJuvenil = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        radioPreJuvenil = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        comboSede = new javax.swing.JComboBox();
        btnCancelar = new javax.swing.JButton();
        btnInscribirParticipantes = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(706, 566));
        setMinimumSize(new java.awt.Dimension(706, 566));
        setLayout(null);

        radioZonal1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        radioZonal1.setText("Zonal");
        radioZonal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioZonal1ActionPerformed(evt);
            }
        });

        radioNacional1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        radioNacional1.setText("Nacional");
        radioNacional1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNacional1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText(" Tipo torneo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 273, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioZonal1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioNacional1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioZonal1, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioNacional1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(jPanel2);
        jPanel2.setBounds(510, 120, 543, 75);
        add(jSeparator2);
        jSeparator2.setBounds(510, 320, 543, 12);
        add(jSeparator3);
        jSeparator3.setBounds(510, 410, 543, 10);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Tipo torneo");

        radioSimple.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        radioSimple.setText("Simple");
        radioSimple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSimpleActionPerformed(evt);
            }
        });

        radioDoble.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        radioDoble.setText("Doble");
        radioDoble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioDobleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 267, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioDoble, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioSimple, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(radioSimple))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioDoble)
                .addContainerGap())
        );

        add(jPanel3);
        jPanel3.setBounds(510, 330, 543, 71);
        add(jSeparator1);
        jSeparator1.setBounds(510, 200, 543, 10);

        radioAbierto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        radioAbierto.setText("Abierto");
        radioAbierto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioAbiertoActionPerformed(evt);
            }
        });

        radioJuvenil.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        radioJuvenil.setText("Juvenil");
        radioJuvenil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioJuvenilActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText(" Categoria Jugador");

        radioPreJuvenil.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        radioPreJuvenil.setText("Pre-Juvenil");
        radioPreJuvenil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioPreJuvenilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 262, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioJuvenil, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioPreJuvenil, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioAbierto, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioPreJuvenil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioJuvenil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 5, Short.MAX_VALUE)
                .addComponent(radioAbierto)
                .addContainerGap())
        );

        add(jPanel4);
        jPanel4.setBounds(510, 210, 543, 103);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText(" Sede");

        comboSede.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Quito", "Guayaquil", "Cuenca" }));
        comboSede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSedeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 253, Short.MAX_VALUE)
                .addComponent(comboSede, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboSede, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        add(jPanel5);
        jPanel5.setBounds(510, 420, 543, 60);

        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        add(btnCancelar);
        btnCancelar.setBounds(860, 500, 190, 50);

        btnInscribirParticipantes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnInscribirParticipantes.setText("Crear torneo");
        btnInscribirParticipantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInscribirParticipantesActionPerformed(evt);
            }
        });
        add(btnInscribirParticipantes);
        btnInscribirParticipantes.setBounds(510, 500, 200, 50);

        jLabel6.setFont(new java.awt.Font("Impact", 0, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Creación de Torneo");
        add(jLabel6);
        jLabel6.setBounds(660, 40, 250, 28);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ucuenca/p3/Iconos/fondo6.jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 1190, 656);
    }// </editor-fold>//GEN-END:initComponents

    public void ingresarTorneo(String codigo, String tipo, String tipoJuego, String categoria) {
        TorneoSRV torneoSrv = new TorneoSRV();
        try {
            torneoSrv.crearTorneo(codigo, tipo, tipoJuego, categoria);

        } catch (TorneoExistenteExcepcion ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }


    private void radioZonal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioZonal1ActionPerformed
        if (radioZonal1.isSelected() == true) {
            radioPreJuvenil.setEnabled(true);
            radioJuvenil.setEnabled(true);
            radioAbierto.setEnabled(true);
            radioNacional1.setEnabled(false);

            radioPreJuvenil.setSelected(false);
            radioJuvenil.setSelected(false);
            radioAbierto.setSelected(false);

            radioSimple.setEnabled(false);
            radioDoble.setEnabled(false);
            comboSede.setEnabled(false);
        } else {
            radioPreJuvenil.setEnabled(false);
            radioJuvenil.setEnabled(false);
            radioAbierto.setEnabled(false);
            radioNacional1.setEnabled(true);
            btnInscribirParticipantes.setEnabled(false);

            radioSimple.setEnabled(false);
            radioDoble.setEnabled(false);
            comboSede.setEnabled(false);
        }
    }//GEN-LAST:event_radioZonal1ActionPerformed

    private void radioNacional1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNacional1ActionPerformed
        if (radioNacional1.isSelected() == true) {
            radioPreJuvenil.setEnabled(true);
            radioJuvenil.setEnabled(true);
            radioAbierto.setEnabled(true);
            radioZonal1.setEnabled(false);

            radioPreJuvenil.setSelected(false);
            radioJuvenil.setSelected(false);
            radioAbierto.setSelected(false);

            radioSimple.setEnabled(false);
            radioDoble.setEnabled(false);
            comboSede.setEnabled(false);
        } else {
            radioPreJuvenil.setEnabled(false);
            radioJuvenil.setEnabled(false);
            radioAbierto.setEnabled(false);
            radioZonal1.setEnabled(true);

            radioSimple.setEnabled(false);
            radioDoble.setEnabled(false);
            comboSede.setEnabled(false);
        }
    }//GEN-LAST:event_radioNacional1ActionPerformed

    private void radioSimpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSimpleActionPerformed
        if (radioSimple.isSelected() == true) {
            radioDoble.setEnabled(false);
            comboSede.setEnabled(true);
        } else {
            radioDoble.setEnabled(true);
            comboSede.setEnabled(false);
            btnInscribirParticipantes.setEnabled(false);
        }
    }//GEN-LAST:event_radioSimpleActionPerformed

    private void radioDobleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioDobleActionPerformed
        if (radioDoble.isSelected() == true) {
            radioSimple.setEnabled(false);
            comboSede.setEnabled(true);
        } else {
            radioSimple.setEnabled(true);
            comboSede.setEnabled(false);
            btnInscribirParticipantes.setEnabled(false);
        }
    }//GEN-LAST:event_radioDobleActionPerformed

    private void radioAbiertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioAbiertoActionPerformed
        if (radioAbierto.isSelected() == true) {
            radioJuvenil.setEnabled(false);
            radioPreJuvenil.setEnabled(false);

            radioSimple.setSelected(false);
            radioDoble.setSelected(false);

            if (radioZonal1.isSelected() == true) {
                radioSimple.setEnabled(true);
                radioDoble.setEnabled(true);
            } else if (radioNacional1.isSelected() == true) {
                radioSimple.setEnabled(true);
                radioDoble.setEnabled(false);
            }
        } else {
            radioJuvenil.setEnabled(true);
            radioPreJuvenil.setEnabled(true);
            radioSimple.setEnabled(false);
            radioDoble.setEnabled(false);
            btnInscribirParticipantes.setEnabled(false);
        }
    }//GEN-LAST:event_radioAbiertoActionPerformed

    private void radioJuvenilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioJuvenilActionPerformed
        if (radioJuvenil.isSelected() == true) {
            radioPreJuvenil.setEnabled(false);
            radioAbierto.setEnabled(false);

            radioSimple.setSelected(false);
            radioDoble.setSelected(false);
            if (radioZonal1.isSelected() == true) {
                radioSimple.setEnabled(true);
                radioDoble.setEnabled(true);
            } else if (radioNacional1.isSelected() == true) {
                radioSimple.setEnabled(true);
                radioDoble.setEnabled(false);
            }
        } else {
            radioPreJuvenil.setEnabled(true);
            radioAbierto.setEnabled(true);
            radioSimple.setEnabled(false);
            radioDoble.setEnabled(false);
            btnInscribirParticipantes.setEnabled(false);
        }
    }//GEN-LAST:event_radioJuvenilActionPerformed

    private void radioPreJuvenilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioPreJuvenilActionPerformed
        if (radioPreJuvenil.isSelected() == true) {
            radioJuvenil.setEnabled(false);
            radioAbierto.setEnabled(false);

            radioSimple.setSelected(false);
            radioDoble.setSelected(false);

            if (radioZonal1.isSelected() == true) {
                radioSimple.setEnabled(true);
                radioDoble.setEnabled(true);
            } else if (radioNacional1.isSelected() == true) {
                radioSimple.setEnabled(true);
                radioDoble.setEnabled(false);
            }
        } else {
            radioJuvenil.setEnabled(true);
            radioAbierto.setEnabled(true);
            radioSimple.setEnabled(false);
            radioDoble.setEnabled(false);
            btnInscribirParticipantes.setEnabled(false);
        }
    }//GEN-LAST:event_radioPreJuvenilActionPerformed


    private void comboSedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSedeActionPerformed
        String ciudad = "";
        ciudad = (String) comboSede.getSelectedItem();
        System.out.println("Sede : " + ciudad);
        if (ciudad != null) {
            btnInscribirParticipantes.setEnabled(true);
        } else {
            btnInscribirParticipantes.setEnabled(false);
        }
    }//GEN-LAST:event_comboSedeActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpiarRadioButton();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnInscribirParticipantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscribirParticipantesActionPerformed

        String tipo = "";
        String tipo_juego = "";
        String categoria = "";
        if (radioZonal1.isSelected()) {
            tipo = "Zonal";
        } else if (radioNacional1.isSelected()) {
            tipo = "Nacional";
        }

        if (radioPreJuvenil.isSelected()) {
            categoria = "Pre Juvenil";
        } else if (radioJuvenil.isSelected()) {
            categoria = "Juvenil";
        } else if (radioAbierto.isSelected()) {
            categoria = "Abierta";
        }

        if (radioSimple.isSelected()) {
            tipo_juego = "Simple";
        } else if (radioDoble.isSelected()) {
            tipo_juego = "Doble";
        }
        String codigo = JOptionPane.showInputDialog("Ingrese código del torneo: ", JOptionPane.QUESTION_MESSAGE);
        if (codigo != null) {
            TorneoSRV torneoSrv = new TorneoSRV();
            if (torneoSrv.existeTorneo(codigo) == false) {
                //ingresarTorneo(codigo, tipo, tipo_juego, categoria);

                try {
                    torneoSrv.crearTorneo(codigo, tipo, tipo_juego, categoria);

                } catch (TorneoExistenteExcepcion ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
                JOptionPane.showMessageDialog(null, "Ingreso exitoso del torneo");
                limpiarRadioButton();

            } else {
                JOptionPane.showMessageDialog(null, "El torneo con codigo " + codigo + " ya existe.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Creación de torneo fallido!");
        }
    }//GEN-LAST:event_btnInscribirParticipantesActionPerformed

    private void limpiarRadioButton() {
        radioZonal1.setSelected(false);
        radioNacional1.setSelected(false);
        radioPreJuvenil.setSelected(false);
        radioJuvenil.setSelected(false);
        radioAbierto.setSelected(false);
        radioSimple.setSelected(false);
        radioDoble.setSelected(false);

        radioZonal1.setEnabled(true);
        radioNacional1.setEnabled(true);
        radioPreJuvenil.setEnabled(false);
        radioJuvenil.setEnabled(false);
        radioAbierto.setEnabled(false);
        radioSimple.setEnabled(false);
        radioDoble.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnInscribirParticipantes;
    private javax.swing.JComboBox comboSede;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JRadioButton radioAbierto;
    private javax.swing.JRadioButton radioDoble;
    private javax.swing.JRadioButton radioJuvenil;
    private javax.swing.JRadioButton radioNacional1;
    private javax.swing.JRadioButton radioPreJuvenil;
    private javax.swing.JRadioButton radioSimple;
    private javax.swing.JRadioButton radioZonal1;
    // End of variables declaration//GEN-END:variables
}
